// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJPDTNZdwFTCradY5QAP4RR6oSVklRUng',
    appId: '1:406744694169:web:3abbdb3167c451bca06708',
    messagingSenderId: '406744694169',
    projectId: 'chatapp-sxjal',
    authDomain: 'chatapp-sxjal.firebaseapp.com',
    storageBucket: 'chatapp-sxjal.appspot.com',
    measurementId: 'G-QW11C6N17B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv7cPDy7iSYB3KJAZNsibxuW-XJNpAeyM',
    appId: '1:406744694169:android:334cc446ff79aacfa06708',
    messagingSenderId: '406744694169',
    projectId: 'chatapp-sxjal',
    storageBucket: 'chatapp-sxjal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCANldjfRPaZov39g324ZCGbxJyjEgzRDw',
    appId: '1:406744694169:ios:ea010727df3a0368a06708',
    messagingSenderId: '406744694169',
    projectId: 'chatapp-sxjal',
    storageBucket: 'chatapp-sxjal.appspot.com',
    iosClientId:
        '406744694169-heq9pd6f4jh1dnpob095ufqpfl8cs3ml.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCANldjfRPaZov39g324ZCGbxJyjEgzRDw',
    appId: '1:406744694169:ios:b292b7c61505dd9da06708',
    messagingSenderId: '406744694169',
    projectId: 'chatapp-sxjal',
    storageBucket: 'chatapp-sxjal.appspot.com',
    iosClientId:
        '406744694169-4jg3iieijvvp1k2uoiggkfgtsrm9g7du.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
